<a href="https://colab.research.google.com/github/Arif118/Heart-disease-prediction/blob/main/Heart_disease_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv('/content/heart.xls')
df1.head(4)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0

In [ ]:
df1.shape

(1025, 14)

In [ ]:
df2 = pd.read_csv('/content/heart(2).xls')
df2.head(4)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1

In [ ]:
df2['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [ ]:
df2['cp'] = df2['ChestPainType'].map({
    'ASY': 0,
    'ATA': 1,
    'NAP': 1,
    'TA': 1
})

In [ ]:
df2['RestingECG_type'] = df2['RestingECG']

In [ ]:
df2['RestingECG'] = df2['RestingECG'].map({
   'Normal': 0,
   'ST': 1,
   'LVH': 1
})

In [ ]:
df2

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,cp,RestingECG_type
0,40,M,ATA,140,289,0,0,172,N,0.0,Up,0,1,Normal
1,49,F,NAP,160,180,0,0,156,N,1.0,Flat,1,1,Normal
2,37,M,ATA,130,283,0,1,98,N,0.0,Up,0,1,ST
3,48,F,ASY,138,214,0,0,108,Y,1.5,Flat,1,0,Normal
4,54,M,NAP,150,195,0,0,122,N,0.0,Up,0,1,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,0,132,N,1.2,Flat,1,1,Normal
914,68,M,ASY,144,193,1,0,141,N,3.4,Flat,1,0,Normal
915,57,M,ASY,130,131,0,0,115,Y,1.2,Flat,1,0,Normal
916,57,F,ATA,130,236,0,1,174,N,0.0,Flat,1,1,LVH
917,38,M,NAP,138,175,0,0,173,N,0.0,Up,0,1,Normal

In [ ]:
df_extra = [df1['ca'],df1['thal'],df2['ChestPainType'],df2['RestingECG_type']]

In [ ]:
df1= df1.drop(['ca','thal'],axis=1)
df2= df2.drop(['ChestPainType','RestingECG_type'],axis=1)

In [ ]:
df2

,Age,Sex,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,cp
0,40,M,140,289,0,0,172,N,0.0,Up,0,1
1,49,F,160,180,0,0,156,N,1.0,Flat,1,1
2,37,M,130,283,0,1,98,N,0.0,Up,0,1
3,48,F,138,214,0,0,108,Y,1.5,Flat,1,0
4,54,M,150,195,0,0,122,N,0.0,Up,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,110,264,0,0,132,N,1.2,Flat,1,1
914,68,M,144,193,1,0,141,N,3.4,Flat,1,0
915,57,M,130,131,0,0,115,Y,1.2,Flat,1,0
916,57,F,130,236,0,1,174,N,0.0,Flat,1,1
917,38,M,138,175,0,0,173,N,0.0,Up,0,1

In [ ]:
df1.columns = ['Age','Sex','cp','RestingBP','Cholesterol','FastingBS','RestingECG','MaxHR','ExerciseAngina','Oldpeak','ST_Slope','HeartDisease']

In [ ]:
df = pd.concat([df1,df2])
df

,Age,Sex,cp,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,52,1,0,125,212,0,1,168,0,1.0,2,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0
3,61,1,0,148,203,0,1,161,0,0.0,2,0
4,62,0,0,138,294,1,1,106,0,1.9,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,1,110,264,0,0,132,N,1.2,Flat,1
914,68,M,0,144,193,1,0,141,N,3.4,Flat,1
915,57,M,0,130,131,0,0,115,Y,1.2,Flat,1
916,57,F,1,130,236,0,1,174,N,0.0,Flat,1
917,38,M,1,138,175,0,0,173,N,0.0,Up,0

# Encoding DF2

In [ ]:
from sklearn.preprocessing import LabelEncoder

le= LabelEncoder()
df2['Sex'] = le.fit_transform(df2['Sex'])
df2['ExerciseAngina'] = le.fit_transform(df2['ExerciseAngina'])

In [ ]:
df2['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [ ]:
df2['ST_Slope'] = df2['ST_Slope'].map({
    'Down': 0,
    'Flat': 0.5,
    'Up': 1
})

In [ ]:
df2

,Age,Sex,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,cp
0,40,1,140,289,0,0,172,0,0.0,1.0,0,1
1,49,0,160,180,0,0,156,0,1.0,0.5,1,1
2,37,1,130,283,0,1,98,0,0.0,1.0,0,1
3,48,0,138,214,0,0,108,1,1.5,0.5,1,0
4,54,1,150,195,0,0,122,0,0.0,1.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,0,132,0,1.2,0.5,1,1
914,68,1,144,193,1,0,141,0,3.4,0.5,1,0
915,57,1,130,131,0,0,115,1,1.2,0.5,1,0
916,57,0,130,236,0,1,174,0,0.0,0.5,1,1
917,38,1,138,175,0,0,173,0,0.0,1.0,0,1